name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - name: Build the Docker image
      run: docker build . --tag ${{secrets.DOCKERHUB_USERNAME}}/gsmanager:latest
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/gsmanager:latest
